/*$DELIMITER:/ */
CREATE TABLE JCR_MCONTAINER(
  VERSION VARCHAR2(96) NOT NULL,
  CONSTRAINT JCR_PK_MCONTAINER PRIMARY KEY(VERSION)
)
/
CREATE TABLE JCR_MITEM(
	ID VARCHAR2(96) NOT NULL,
	PARENT_ID VARCHAR2(96) NOT NULL,
	NAME VARCHAR2(512) NOT NULL,
	VERSION INTEGER NOT NULL,
	I_CLASS INTEGER NOT NULL,
	I_INDEX INTEGER NOT NULL,
	N_ORDER_NUM INTEGER,
	P_TYPE INTEGER, 
	P_MULTIVALUED INTEGER,	
	CONSTRAINT JCR_PK_MITEM PRIMARY KEY(ID),
	CONSTRAINT JCR_FK_MITEM_PARENT FOREIGN KEY(PARENT_ID) REFERENCES JCR_MITEM(ID)
	)
/
CREATE INDEX JCR_IDX_MITEM_PARENT_FK ON JCR_MITEM(PARENT_ID)
/
CREATE UNIQUE INDEX JCR_IDX_MITEM_PARENT ON JCR_MITEM( PARENT_ID, NAME, I_INDEX, I_CLASS, VERSION DESC)
/
CREATE UNIQUE INDEX JCR_IDX_MITEM_PARENT_NAME ON JCR_mITEM(I_CLASS, PARENT_ID, NAME, I_INDEX, VERSION DESC)
/
CREATE UNIQUE INDEX JCR_IDX_MITEM_PARENT_ID ON JCR_MITEM(I_CLASS, PARENT_ID, ID, VERSION DESC)
/
CREATE TABLE JCR_MVALUE(
	DATA BLOB, 
	ORDER_NUM INTEGER NOT NULL, 
	PROPERTY_ID VARCHAR(96) NOT NULL,
	STORAGE_DESC VARCHAR(512),
	CONSTRAINT JCR_PK_MVALUE PRIMARY KEY(PROPERTY_ID, ORDER_NUM),
	CONSTRAINT JCR_FK_MVALUE_PROPERTY FOREIGN KEY(PROPERTY_ID) REFERENCES JCR_MITEM(ID)
	)
/
CREATE TABLE JCR_MREF(
  NODE_ID VARCHAR(96) NOT NULL,
  PROPERTY_ID VARCHAR(96) NOT NULL,
  ORDER_NUM INTEGER NOT NULL,
  CONSTRAINT JCR_PK_MREF PRIMARY KEY(NODE_ID, PROPERTY_ID, ORDER_NUM)
)
/
CREATE UNIQUE INDEX JCR_IDX_MREF_PROPERTY ON JCR_MREF(PROPERTY_ID, ORDER_NUM)
/






ANALYZE INDEX JCR_PK_SITEM COMPUTE STATISTICS
/
ANALYZE INDEX JCR_IDX_MITEM_ID COMPUTE STATISTICS
/
ANALYZE INDEX JCR_IDX_MITEM_PATH COMPUTE STATISTICS
/
ANALYZE INDEX JCR_PK_MNODE COMPUTE STATISTICS
/
ANALYZE INDEX JCR_IDX_MNODE_PARENT COMPUTE STATISTICS
/
ANALYZE INDEX JCR_IDX_MNODE_PARENTID COMPUTE STATISTICS
/
ANALYZE INDEX JCR_PK_MPROPERTY COMPUTE STATISTICS
/
ANALYZE INDEX JCR_IDX_MPROPERTY_PARENT COMPUTE STATISTICS
/
ANALYZE INDEX JCR_IDX_MPROPERTY_PARENTID COMPUTE STATISTICS
/
ANALYZE INDEX JCR_PK_MVALUE COMPUTE STATISTICS
/
ANALYZE INDEX JCR_IDX_MVALUE_PROPERTY COMPUTE STATISTICS
/
ANALYZE INDEX JCR_PK_MREF COMPUTE STATISTICS
/
ANALYZE INDEX JCR_IDX_MREF_PROPERTY COMPUTE STATISTICS
/