CREATE TABLE ${table.name}(
  NODE_ID VARCHAR(96) NOT NULL,
  TOKEN_HASH VARCHAR(32) NOT NULL,
  OWNER VARCHAR(96) NOT NULL,
  IS_SESSIONSCOPED CHAR NOT NULL,
  IS_DEEP CHAR NOT NULL,
  BIRTHDAY BIGINT NOT NULL,
  TIMEOUT BIGINT NOT NULL
);